[package]
name = "lab"
version = "0.1.0"
authors = ["Nico Chatzi <nico.chatzigianis@focusrite.com>"]
edition = "2018"
publish = false

[dependencies]
rume = { path = "../../rume", features = ["lab"] }