on: [push]

name: CI

jobs:
  build_and_test:
    name: Run crate tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test workspace
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build examples
        uses: actions-rs/cargo@v1
        with:
          command: build --examples