name: main ci

on: [push]

jobs:
  build_and_test:
    name: build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: target
          key: cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast

      - name: Run linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings